version: '3.8'
services:
   db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=0000
    ports:
      - '5432:5432'
    volumes:
      - .db/:/var/lib/postgresql/data
volumes:
  db:
    driver: local